const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
const REQUEST_START = 'REQUEST_START';
const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_FAILED = 'REQUEST_FAILED';

export {
  LOGIN_FORM_SUBMIT,
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_FAILED };
