const LOGIN_FORM_SUBMIT = 'LOGIN_FORM_SUBMIT';
const REQUEST_START = 'REQUEST_START';
const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_FAILED = 'REQUEST_FAILED';
const ADD_EXPENSE = 'ADD_EXPENSE';
const DELETE_EXPENSE = 'DELETE_EXPENSE';

export {
  LOGIN_FORM_SUBMIT,
  REQUEST_START,
  REQUEST_SUCCESS,
  REQUEST_FAILED,
  ADD_EXPENSE,
  DELETE_EXPENSE };
